export const LOCATIONS = [

  // ── CITY: Urban & Street ─────────────────────────────────────────────────
  {
    id: 'pike-place',
    name: 'Pike Place Market',
    category: 'city', subcategory: 'Urban & Street',
    lat: 47.6097, lng: -122.3421, distanceMiles: 0,
    notes: 'Fish throwers, flower stalls, the original Starbucks — arrive before 9am to beat crowds',
    wikiTitle: 'Pike Place Market',
  },
  {
    id: 'post-alley',
    name: 'Post Alley & Gum Wall',
    category: 'city', subcategory: 'Urban & Street',
    lat: 47.6088, lng: -122.3398, distanceMiles: 0,
    notes: 'Colorful brick alley layered with gum art since the 1990s — quirky and photogenic',
    wikiTitle: 'Market Theater Gum Wall',
  },
  {
    id: 'capitol-hill',
    name: 'Capitol Hill',
    category: 'city', subcategory: 'Urban & Street',
    lat: 47.6205, lng: -122.3212, distanceMiles: 1,
    notes: 'Street murals, indie cafes, and nightlife neon — great for moody street photography',
    wikiTitle: 'Capitol Hill, Seattle',
  },
  {
    id: 'fremont',
    name: 'Fremont Neighborhood',
    category: 'city', subcategory: 'Urban & Street',
    lat: 47.6517, lng: -122.3501, distanceMiles: 3,
    notes: "Bohemian district with the famous Fremont Troll, vintage shops, and canal views",
    wikiTitle: 'Fremont Troll',
  },
  {
    id: 'georgetown',
    name: 'Georgetown Murals',
    category: 'city', subcategory: 'Urban & Street',
    lat: 47.5551, lng: -122.3244, distanceMiles: 5,
    notes: 'Industrial warehouse district turned open-air mural gallery — gritty and creative',
    wikiTitle: 'Georgetown, Seattle',
  },

  // ── CITY: Architecture ────────────────────────────────────────────────────
  {
    id: 'space-needle',
    name: 'Space Needle',
    category: 'city', subcategory: 'Architecture',
    lat: 47.6205, lng: -122.3493, distanceMiles: 0,
    notes: '605-foot icon — shoot from below at dusk or frame it from Kerry Park across the skyline',
    wikiTitle: 'Space Needle',
  },
  {
    id: 'central-library',
    name: 'Seattle Central Library',
    category: 'city', subcategory: 'Architecture',
    lat: 47.6068, lng: -122.3309, distanceMiles: 0,
    notes: 'Rem Koolhaas glass diamond — the interior green-tinted spiral filters light beautifully',
    wikiTitle: 'Seattle Central Library',
  },
  {
    id: 'king-street-station',
    name: 'King Street Station',
    category: 'city', subcategory: 'Architecture',
    lat: 47.5981, lng: -122.3293, distanceMiles: 1,
    notes: '1906 Romanesque Revival station with ornate coffered ceilings — stunning interior shots',
    wikiTitle: 'King Street station (Seattle)',
  },

  // ── CITY: Waterfront ──────────────────────────────────────────────────────
  {
    id: 'olympic-sculpture',
    name: 'Olympic Sculpture Park',
    category: 'city', subcategory: 'Waterfront',
    lat: 47.6128, lng: -122.3582, distanceMiles: 0,
    notes: "9-acre free park where modern art meets Elliott Bay — Serra's Eagle frames water and mountains",
    wikiTitle: 'Olympic Sculpture Park',
  },
  {
    id: 'alki-beach',
    name: 'Alki Beach',
    category: 'city', subcategory: 'Waterfront',
    lat: 47.5757, lng: -122.4151, distanceMiles: 5,
    notes: "West Seattle's sandy beach — the full downtown skyline reflected in Puget Sound at sunset",
    wikiTitle: 'Alki Beach Park',
  },
  {
    id: 'ballard-locks',
    name: 'Hiram M. Chittenden Locks',
    category: 'city', subcategory: 'Waterfront',
    lat: 47.6680, lng: -122.3891, distanceMiles: 6,
    notes: 'Watch boats lock through and salmon jump the fish ladder — unique industrial waterway scene',
    wikiTitle: 'Hiram M. Chittenden Locks',
  },

  // ── CITY: City Parks ──────────────────────────────────────────────────────
  {
    id: 'gasworks',
    name: 'Gas Works Park',
    category: 'city', subcategory: 'City Parks',
    lat: 47.6452, lng: -122.3318, distanceMiles: 2,
    notes: 'Rusted industrial towers on a grassy hilltop — panoramic Lake Union and skyline views',
    wikiTitle: 'Gas Works Park',
  },
  {
    id: 'volunteer-park',
    name: 'Volunteer Park',
    category: 'city', subcategory: 'City Parks',
    lat: 47.6260, lng: -122.3036, distanceMiles: 2,
    notes: 'Water tower deck, lily pond, and dahlia gardens — each season transforms the palette',
    wikiTitle: 'Volunteer Park (Seattle)',
  },
  {
    id: 'discovery-park',
    name: 'Discovery Park',
    category: 'city', subcategory: 'City Parks',
    lat: 47.6620, lng: -122.4357, distanceMiles: 5,
    notes: "West Point Lighthouse on sea cliffs — Seattle's largest park with Olympic and Cascade views",
    wikiTitle: 'Discovery Park (Seattle)',
  },
  {
    id: 'arboretum',
    name: 'Washington Park Arboretum',
    category: 'city', subcategory: 'City Parks',
    lat: 47.6367, lng: -122.2985, distanceMiles: 3,
    notes: '230 acres of maples, cherries, and camellias — Japanese Garden is a highlight year-round',
    wikiTitle: 'Washington Park Arboretum',
  },

  // ── VIEWPOINTS: City Skyline ──────────────────────────────────────────────
  {
    id: 'kerry-park',
    name: 'Kerry Park',
    category: 'viewpoint', subcategory: 'City Skyline',
    lat: 47.6245, lng: -122.3559, distanceMiles: 1,
    notes: 'THE Seattle shot — Space Needle, downtown, and Mt Rainier all in one frame at golden hour',
    wikiTitle: 'Kerry Park (Seattle)',
  },
  {
    id: 'queen-anne',
    name: 'Queen Anne Hill',
    category: 'viewpoint', subcategory: 'City Skyline',
    lat: 47.6323, lng: -122.3576, distanceMiles: 2,
    notes: 'Multiple overlooks along the ridge — less crowded than Kerry Park, same great skyline angle',
    wikiTitle: 'Queen Anne, Seattle',
  },
  {
    id: 'beacon-hill',
    name: 'Beacon Hill & Jefferson Park',
    category: 'viewpoint', subcategory: 'City Skyline',
    lat: 47.5697, lng: -122.3069, distanceMiles: 3,
    notes: 'Underrated southward skyline view — Rainier frames the cityscape on clear days',
    wikiTitle: 'Beacon Hill, Seattle',
  },
  {
    id: 'parsons-garden',
    name: 'Parsons Garden & Marshall Park',
    category: 'viewpoint', subcategory: 'Hidden Gems',
    lat: 47.6323, lng: -122.3612, distanceMiles: 2,
    notes: 'Secret rose garden with stone staircases — Marshall Park just across has Olympic Mountain views',
    wikiTitle: 'Queen Anne, Seattle',
  },

  // ── VIEWPOINTS: Aerial Views ──────────────────────────────────────────────
  {
    id: 'columbia-tower',
    name: 'Columbia Tower Observatory',
    category: 'viewpoint', subcategory: 'Aerial Views',
    lat: 47.6060, lng: -122.3310, distanceMiles: 0,
    notes: '360° views from 900ft — the only spot in Seattle to look DOWN on the Space Needle',
    wikiTitle: 'Columbia Center',
  },
  {
    id: 'smith-tower',
    name: 'Smith Tower Observatory',
    category: 'viewpoint', subcategory: 'Aerial Views',
    lat: 47.6024, lng: -122.3291, distanceMiles: 0,
    notes: 'Historic 1914 skyscraper, 35th-floor open-air deck — vintage Seattle panorama, bar on-site',
    wikiTitle: 'Smith Tower',
  },

  // ── VIEWPOINTS: Coastal Viewpoints ───────────────────────────────────────
  {
    id: 'richmond-beach',
    name: 'Richmond Beach Saltwater Park',
    category: 'viewpoint', subcategory: 'Coastal Viewpoints',
    lat: 47.7710, lng: -122.3847, distanceMiles: 15,
    notes: 'Bluff trail overlooking Puget Sound and the Olympics — dramatic golden hour light off the water',
    wikiTitle: 'Richmond Beach, Washington',
  },
  {
    id: 'bainbridge-ferry',
    name: 'Bainbridge Island Ferry',
    category: 'viewpoint', subcategory: 'Coastal Viewpoints',
    lat: 47.6256, lng: -122.5237, distanceMiles: 8,
    notes: '35-min ferry crossing — shoot the skyline receding or approaching, incredible at blue hour',
    wikiTitle: 'Bainbridge Island, Washington',
  },

  // ── NATURE: Waterfalls ────────────────────────────────────────────────────
  {
    id: 'snoqualmie-falls',
    name: 'Snoqualmie Falls',
    category: 'nature', subcategory: 'Waterfalls',
    lat: 47.5340, lng: -121.8350, distanceMiles: 28,
    notes: '268ft roaring falls with mist and forest — stunning at full flow in spring',
    wikiTitle: 'Snoqualmie Falls',
  },
  {
    id: 'twin-falls',
    name: 'Twin Falls',
    category: 'nature', subcategory: 'Waterfalls',
    lat: 47.4400, lng: -121.8500, distanceMiles: 32,
    notes: 'Two-tiered waterfall through old-growth moss — easy 2.6mi trail, great for ND long-exposure',
    wikiTitle: 'Twin Falls State Park (Washington)',
  },
  {
    id: 'franklin-falls',
    name: 'Franklin Falls',
    category: 'nature', subcategory: 'Waterfalls',
    lat: 47.4719, lng: -121.5436, distanceMiles: 50,
    notes: 'Dramatic 70ft sheet waterfall — icy and ethereal in winter, flat easy 2mi trail',
    wikiTitle: 'Franklin Falls (Washington)',
  },

  // ── NATURE: Alpine & Mountains ────────────────────────────────────────────
  {
    id: 'rainier-paradise',
    name: 'Mt Rainier — Paradise',
    category: 'nature', subcategory: 'Alpine & Mountains',
    lat: 46.7852, lng: -121.7368, distanceMiles: 90,
    notes: 'Wildflower meadows at 5,400ft with glacier views — alpenglow at golden hour is world-class',
    wikiTitle: 'Paradise, Pierce County, Washington',
  },
  {
    id: 'rainier-reflection',
    name: 'Mt Rainier — Reflection Lakes',
    category: 'nature', subcategory: 'Alpine & Mountains',
    lat: 46.7870, lng: -121.7650, distanceMiles: 92,
    notes: 'Still water mirror of Rainier at sunrise — one of the most iconic shots in the PNW',
    wikiTitle: 'Mount Rainier National Park',
  },
  {
    id: 'rainier-tipsoo',
    name: 'Mt Rainier — Tipsoo Lake',
    category: 'nature', subcategory: 'Alpine & Mountains',
    lat: 46.8691, lng: -121.5175, distanceMiles: 75,
    notes: 'East-side alpine lake surrounded by wildflowers and fall colors — Rainier reflected in still water',
    wikiTitle: 'Tipsoo Lake',
  },

  // ── NATURE: Forests & Trails ──────────────────────────────────────────────
  {
    id: 'rattlesnake',
    name: 'Rattlesnake Ledge',
    category: 'nature', subcategory: 'Forests & Trails',
    lat: 47.4347, lng: -121.7687, distanceMiles: 35,
    notes: 'Exposed rock ledge with Cedar River valley panorama — 4mi RT, accessible year-round',
    wikiTitle: 'Rattlesnake Mountain Scenic Area',
  },
  {
    id: 'mount-si',
    name: 'Mount Si',
    category: 'nature', subcategory: 'Forests & Trails',
    lat: 47.4425, lng: -121.9776, distanceMiles: 30,
    notes: 'Strenuous 8mi RT — dramatic summit views of Cascade foothills and Snoqualmie Valley',
    wikiTitle: 'Mount Si',
  },
  {
    id: 'tiger-mountain',
    name: 'Tiger Mountain — West Tiger 3',
    category: 'nature', subcategory: 'Forests & Trails',
    lat: 47.5010, lng: -121.9805, distanceMiles: 25,
    notes: 'Dense Northwest forest opens to a bald summit with Lake Sammamish and Cascade views',
    wikiTitle: 'Tiger Mountain State Forest',
  },

  // ── NATURE: City Parks & Forests ─────────────────────────────────────────
  {
    id: 'seward-park',
    name: 'Seward Park',
    category: 'nature', subcategory: 'City Parks & Forests',
    lat: 47.5513, lng: -122.2530, distanceMiles: 7,
    notes: '300-acre old-growth forest peninsula — eagle nests + full downtown skyline across Lake Washington',
    wikiTitle: 'Seward Park (Seattle)',
  },
  {
    id: 'lincoln-park',
    name: 'Lincoln Park',
    category: 'nature', subcategory: 'City Parks & Forests',
    lat: 47.5289, lng: -122.3926, distanceMiles: 8,
    notes: 'Puget Sound beachfront + forested bluff — Olympic Mountains as your backdrop at sunset',
    wikiTitle: 'Lincoln Park (Seattle)',
  },
  {
    id: 'carkeek-park',
    name: 'Carkeek Park',
    category: 'nature', subcategory: 'City Parks & Forests',
    lat: 47.7124, lng: -122.3763, distanceMiles: 8,
    notes: 'Driftwood beach + old-growth ravine — passing freight trains add drama, minimal crowds',
    wikiTitle: 'Carkeek Park',
  },
  {
    id: 'bellevue-botanical',
    name: 'Bellevue Botanical Garden',
    category: 'nature', subcategory: 'City Parks & Forests',
    lat: 47.5935, lng: -122.1699, distanceMiles: 12,
    notes: 'Manicured paths, footbridges, and seasonal blooms — polished garden aesthetic year-round',
    wikiTitle: 'Bellevue Botanical Garden',
  },

  // ── NATURE: Lakes & Rivers ────────────────────────────────────────────────
  {
    id: 'lake-serene',
    name: 'Lake Serene',
    category: 'nature', subcategory: 'Lakes & Rivers',
    lat: 47.8198, lng: -121.2668, distanceMiles: 55,
    notes: 'Pristine glacial lake below Index Town Wall — glass-still mirror reflections on calm mornings',
    wikiTitle: 'Lake Serene (Washington)',
  },
  {
    id: 'green-lake',
    name: 'Green Lake Park',
    category: 'nature', subcategory: 'Lakes & Rivers',
    lat: 47.6781, lng: -122.3345, distanceMiles: 3,
    notes: 'Urban lake with sunrise reflections, herons, and swans — a perfect first-light shoot in the city',
    wikiTitle: 'Green Lake Park',
  },
  {
    id: 'magnuson-park',
    name: 'Magnuson Park',
    category: 'nature', subcategory: 'Lakes & Rivers',
    lat: 47.6847, lng: -122.2580, distanceMiles: 7,
    notes: 'Mile-long Lake Washington shoreline with open meadow — great first-light reflections and wide skies',
    wikiTitle: 'Warren G. Magnuson Park',
  },
];

export const WEBCAMS = [
  {
    id: 'nps-paradise',
    label: 'Mt Rainier — Paradise',
    sublabel: 'National Park Service',
    type: 'img',
    url: 'https://www.nps.gov/webcams-mora/mountain.jpg',
    sourceUrl: 'https://www.nps.gov/mora/learn/photosmultimedia/webcams.htm',
  },
  {
    id: 'nps-east',
    label: 'Mt Rainier — East View',
    sublabel: 'National Park Service',
    type: 'img',
    url: 'https://www.nps.gov/webcams-mora/east.jpg',
    sourceUrl: 'https://www.nps.gov/mora/learn/photosmultimedia/webcams.htm',
  },
  {
    id: 'nps-tatoosh',
    label: 'Mt Rainier — Tatoosh Range',
    sublabel: 'National Park Service',
    type: 'img',
    url: 'https://www.nps.gov/webcams-mora/tatoosh.jpg',
    sourceUrl: 'https://www.nps.gov/mora/learn/photosmultimedia/webcams.htm',
  },
  {
    id: 'uw-rainier',
    label: 'UW Campus — Mt Rainier View',
    sublabel: 'UW Atmospheric Sciences',
    type: 'img',
    url: 'https://a.atmos.washington.edu/data/images/webcam2_latest.jpg',
    sourceUrl: 'https://a.atmos.washington.edu/data/webcams.html',
  },
  {
    id: 'wsdot-snq-east',
    label: 'Snoqualmie Pass — East',
    sublabel: 'Washington State DOT',
    type: 'img',
    url: 'https://images.wsdot.wa.gov/airports/hyakeast.jpg',
    sourceUrl: 'https://wsdot.wa.gov/travel/real-time/mountainpasses/Snoqualmie',
  },
  {
    id: 'wsdot-snq-west',
    label: 'Snoqualmie Pass — West',
    sublabel: 'Washington State DOT',
    type: 'img',
    url: 'https://images.wsdot.wa.gov/airports/hyakwest.jpg',
    sourceUrl: 'https://wsdot.wa.gov/travel/real-time/mountainpasses/Snoqualmie',
  },
];
