const UNS = (id) => `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=800&q=80`;
const WIKI = (path) => `https://upload.wikimedia.org/wikipedia/commons/thumb/${path}`;

export const LOCATIONS = [

  // ── CITY: Urban & Street ─────────────────────────────────────────────────
  {
    id: 'pike-place',
    name: 'Pike Place Market',
    category: 'city', subcategory: 'Urban & Street',
    lat: 47.6097, lng: -122.3421, distanceMiles: 0,
    notes: 'Fish throwers, flower stalls, the original Starbucks — arrive before 9am to beat crowds',
    image: WIKI('2/27/Pike_Place_Market_Sign%2C_Seattle%2C_WA.jpg/800px-Pike_Place_Market_Sign%2C_Seattle%2C_WA.jpg'),
  },
  {
    id: 'post-alley',
    name: 'Post Alley & Gum Wall',
    category: 'city', subcategory: 'Urban & Street',
    lat: 47.6088, lng: -122.3398, distanceMiles: 0,
    notes: 'Colorful brick alley layered with gum art since the 1990s — quirky and photogenic',
    image: UNS('1449824913935-59a10b8d2000'),
  },
  {
    id: 'capitol-hill',
    name: 'Capitol Hill',
    category: 'city', subcategory: 'Urban & Street',
    lat: 47.6205, lng: -122.3212, distanceMiles: 1,
    notes: 'Street murals, indie cafes, and nightlife neon — great for moody street photography',
    image: UNS('1519501025264-65ba15a82390'),
  },
  {
    id: 'fremont',
    name: 'Fremont Neighborhood',
    category: 'city', subcategory: 'Urban & Street',
    lat: 47.6517, lng: -122.3501, distanceMiles: 3,
    notes: "Bohemian district with the famous Fremont Troll, vintage shops, and canal views",
    image: WIKI('9/9a/Fremont_troll_2009.jpg/800px-Fremont_troll_2009.jpg'),
  },
  {
    id: 'georgetown',
    name: 'Georgetown Murals',
    category: 'city', subcategory: 'Urban & Street',
    lat: 47.5551, lng: -122.3244, distanceMiles: 5,
    notes: 'Industrial warehouse district turned open-air mural gallery — gritty and creative',
    image: UNS('1438401171849-74ac270044ee'),
  },

  // ── CITY: Architecture ────────────────────────────────────────────────────
  {
    id: 'space-needle',
    name: 'Space Needle',
    category: 'city', subcategory: 'Architecture',
    lat: 47.6205, lng: -122.3493, distanceMiles: 0,
    notes: '605-foot icon — shoot from below at dusk or frame it from Kerry Park across the skyline',
    image: WIKI('7/71/Space_Needle002.jpg/800px-Space_Needle002.jpg'),
  },
  {
    id: 'central-library',
    name: 'Seattle Central Library',
    category: 'city', subcategory: 'Architecture',
    lat: 47.6068, lng: -122.3309, distanceMiles: 0,
    notes: 'Rem Koolhaas glass diamond — the interior green-tinted spiral filters light beautifully',
    image: WIKI('c/c8/Seattle_Public_Library%2C_Central_Branch.jpg/800px-Seattle_Public_Library%2C_Central_Branch.jpg'),
  },
  {
    id: 'king-street-station',
    name: 'King Street Station',
    category: 'city', subcategory: 'Architecture',
    lat: 47.5981, lng: -122.3293, distanceMiles: 1,
    notes: '1906 Romanesque Revival station with ornate coffered ceilings — stunning interior shots',
    image: WIKI('3/30/King_Street_Station_clock_tower.jpg/800px-King_Street_Station_clock_tower.jpg'),
  },

  // ── CITY: Waterfront ──────────────────────────────────────────────────────
  {
    id: 'olympic-sculpture',
    name: 'Olympic Sculpture Park',
    category: 'city', subcategory: 'Waterfront',
    lat: 47.6128, lng: -122.3582, distanceMiles: 0,
    notes: "9-acre free park where modern art meets Elliott Bay — Serra's Eagle frames water and mountains",
    image: UNS('1520038410233-7141be7e6f97'),
  },
  {
    id: 'alki-beach',
    name: 'Alki Beach',
    category: 'city', subcategory: 'Waterfront',
    lat: 47.5757, lng: -122.4151, distanceMiles: 5,
    notes: "West Seattle's sandy beach — the full downtown skyline reflected in Puget Sound at sunset",
    image: UNS('1697729926633-1d9048a2d60a'),
  },
  {
    id: 'ballard-locks',
    name: 'Hiram M. Chittenden Locks',
    category: 'city', subcategory: 'Waterfront',
    lat: 47.6680, lng: -122.3891, distanceMiles: 6,
    notes: 'Watch boats lock through and salmon jump the fish ladder — unique industrial waterway scene',
    image: WIKI('5/52/Chittenden_locks_2.jpg/800px-Chittenden_locks_2.jpg'),
  },

  // ── CITY: City Parks ──────────────────────────────────────────────────────
  {
    id: 'gasworks',
    name: 'Gas Works Park',
    category: 'city', subcategory: 'City Parks',
    lat: 47.6452, lng: -122.3318, distanceMiles: 2,
    notes: 'Rusted industrial towers on a grassy hilltop — panoramic Lake Union and skyline views',
    image: WIKI('0/0d/Gas_Works_Park_Structures.jpg/800px-Gas_Works_Park_Structures.jpg'),
  },
  {
    id: 'volunteer-park',
    name: 'Volunteer Park',
    category: 'city', subcategory: 'City Parks',
    lat: 47.6260, lng: -122.3036, distanceMiles: 2,
    notes: 'Water tower deck, lily pond, and dahlia gardens — each season transforms the palette',
    image: WIKI('8/84/Seattle_-_Volunteer_Park_water_tower_01.jpg/800px-Seattle_-_Volunteer_Park_water_tower_01.jpg'),
  },
  {
    id: 'discovery-park',
    name: 'Discovery Park',
    category: 'city', subcategory: 'City Parks',
    lat: 47.6620, lng: -122.4357, distanceMiles: 5,
    notes: "West Point Lighthouse on sea cliffs — Seattle's largest park with Olympic and Cascade views",
    image: WIKI('3/33/West_Point_Lighthouse_%28Discovery_Park%2C_Seattle%29.jpg/800px-West_Point_Lighthouse_%28Discovery_Park%2C_Seattle%29.jpg'),
  },
  {
    id: 'arboretum',
    name: 'Washington Park Arboretum',
    category: 'city', subcategory: 'City Parks',
    lat: 47.6367, lng: -122.2985, distanceMiles: 3,
    notes: '230 acres of maples, cherries, and camellias — Japanese Garden is a highlight year-round',
    image: WIKI('c/cf/Seattle_Japanese_Garden_002.jpg/800px-Seattle_Japanese_Garden_002.jpg'),
  },

  // ── VIEWPOINTS: City Skyline ──────────────────────────────────────────────
  {
    id: 'kerry-park',
    name: 'Kerry Park',
    category: 'viewpoint', subcategory: 'City Skyline',
    lat: 47.6245, lng: -122.3559, distanceMiles: 1,
    notes: 'THE Seattle shot — Space Needle, downtown, and Mt Rainier all in one frame at golden hour',
    image: WIKI('3/31/Kerry_Park_at_Night.jpg/800px-Kerry_Park_at_Night.jpg'),
  },
  {
    id: 'queen-anne',
    name: 'Queen Anne Hill',
    category: 'viewpoint', subcategory: 'City Skyline',
    lat: 47.6323, lng: -122.3576, distanceMiles: 2,
    notes: 'Multiple overlooks along the ridge — less crowded than Kerry Park, same great skyline angle',
    image: UNS('1502175353174-a7a70e73b362'),
  },
  {
    id: 'beacon-hill',
    name: 'Beacon Hill & Jefferson Park',
    category: 'viewpoint', subcategory: 'City Skyline',
    lat: 47.5697, lng: -122.3069, distanceMiles: 3,
    notes: 'Underrated southward skyline view — Rainier frames the cityscape on clear days',
    image: UNS('1542223616-9de9adb5e3e8'),
  },
  {
    id: 'parsons-garden',
    name: 'Parsons Garden & Marshall Park',
    category: 'viewpoint', subcategory: 'Hidden Gems',
    lat: 47.6323, lng: -122.3612, distanceMiles: 2,
    notes: 'Secret rose garden with stone staircases — Marshall Park just across has Olympic Mountain views over the Sound',
    image: UNS('1476067897447-90eb35ff6a70'),
  },

  // ── VIEWPOINTS: Aerial Views ──────────────────────────────────────────────
  {
    id: 'columbia-tower',
    name: 'Columbia Tower Observatory',
    category: 'viewpoint', subcategory: 'Aerial Views',
    lat: 47.6060, lng: -122.3310, distanceMiles: 0,
    notes: '360° views from 900ft — the only spot in Seattle to look DOWN on the Space Needle',
    image: UNS('1437809781432-a957377661ee'),
  },
  {
    id: 'smith-tower',
    name: 'Smith Tower Observatory',
    category: 'viewpoint', subcategory: 'Aerial Views',
    lat: 47.6024, lng: -122.3291, distanceMiles: 0,
    notes: 'Historic 1914 skyscraper, 35th-floor open-air deck — vintage Seattle panorama, bar on-site',
    image: WIKI('f/f7/Columbia_Center_from_SN.jpg/800px-Columbia_Center_from_SN.jpg'),
  },

  // ── VIEWPOINTS: Coastal Viewpoints ───────────────────────────────────────
  {
    id: 'richmond-beach',
    name: 'Richmond Beach Saltwater Park',
    category: 'viewpoint', subcategory: 'Coastal Viewpoints',
    lat: 47.7710, lng: -122.3847, distanceMiles: 15,
    notes: 'Bluff trail overlooking Puget Sound and the Olympics — dramatic golden hour light off the water',
    image: UNS('1520038410233-7141be7e6f97'),
  },
  {
    id: 'bainbridge-ferry',
    name: 'Bainbridge Island Ferry',
    category: 'viewpoint', subcategory: 'Coastal Viewpoints',
    lat: 47.6256, lng: -122.5237, distanceMiles: 8,
    notes: '35-min ferry crossing — shoot the skyline receding or approaching, incredible at blue hour',
    image: UNS('1549092273-8b23dde8ac2b'),
  },

  // ── NATURE: Waterfalls ────────────────────────────────────────────────────
  {
    id: 'snoqualmie-falls',
    name: 'Snoqualmie Falls',
    category: 'nature', subcategory: 'Waterfalls',
    lat: 47.5340, lng: -121.8350, distanceMiles: 28,
    notes: '268ft roaring falls with mist and forest — stunning at full flow in spring',
    image: WIKI('0/07/Snoqualmie_Falls_in_2011.jpg/800px-Snoqualmie_Falls_in_2011.jpg'),
  },
  {
    id: 'twin-falls',
    name: 'Twin Falls',
    category: 'nature', subcategory: 'Waterfalls',
    lat: 47.4400, lng: -121.8500, distanceMiles: 32,
    notes: 'Two-tiered waterfall through old-growth moss — easy 2.6mi trail, great for ND long-exposure',
    image: UNS('1552083375-1447ce886485'),
  },
  {
    id: 'franklin-falls',
    name: 'Franklin Falls',
    category: 'nature', subcategory: 'Waterfalls',
    lat: 47.4719, lng: -121.5436, distanceMiles: 50,
    notes: 'Dramatic 70ft sheet waterfall — icy and ethereal in winter, flat easy 2mi trail',
    image: WIKI('e/e2/Franklin_falls_snow_2018.jpg/800px-Franklin_falls_snow_2018.jpg'),
  },

  // ── NATURE: Alpine & Mountains ────────────────────────────────────────────
  {
    id: 'rainier-paradise',
    name: 'Mt Rainier — Paradise',
    category: 'nature', subcategory: 'Alpine & Mountains',
    lat: 46.7852, lng: -121.7368, distanceMiles: 90,
    notes: 'Wildflower meadows at 5,400ft with glacier views — alpenglow at golden hour is world-class',
    image: WIKI('1/10/Mount_Rainier_from_Crystal_Mountain.jpg/800px-Mount_Rainier_from_Crystal_Mountain.jpg'),
  },
  {
    id: 'rainier-reflection',
    name: 'Mt Rainier — Reflection Lakes',
    category: 'nature', subcategory: 'Alpine & Mountains',
    lat: 46.7870, lng: -121.7650, distanceMiles: 92,
    notes: 'Still water mirror of Rainier at sunrise — one of the most iconic shots in the PNW',
    image: WIKI('a/a9/Mount_Rainier_reflected_in_Reflection_Lakes.jpg/800px-Mount_Rainier_reflected_in_Reflection_Lakes.jpg'),
  },
  {
    id: 'rainier-tipsoo',
    name: 'Mt Rainier — Tipsoo Lake',
    category: 'nature', subcategory: 'Alpine & Mountains',
    lat: 46.8691, lng: -121.5175, distanceMiles: 75,
    notes: 'East-side alpine lake surrounded by wildflowers and fall colors — Rainier reflected in still water',
    image: WIKI('6/6c/Tipsoo_Lake.jpg/800px-Tipsoo_Lake.jpg'),
  },

  // ── NATURE: Forests & Trails ──────────────────────────────────────────────
  {
    id: 'rattlesnake',
    name: 'Rattlesnake Ledge',
    category: 'nature', subcategory: 'Forests & Trails',
    lat: 47.4347, lng: -121.7687, distanceMiles: 35,
    notes: 'Exposed rock ledge with Cedar River valley panorama — 4mi RT, accessible year-round',
    image: WIKI('f/f9/Rattlesnake_Ridge_-_Rattlesnake_Ledge_from_below.jpg/800px-Rattlesnake_Ridge_-_Rattlesnake_Ledge_from_below.jpg'),
  },
  {
    id: 'mount-si',
    name: 'Mount Si',
    category: 'nature', subcategory: 'Forests & Trails',
    lat: 47.4425, lng: -121.9776, distanceMiles: 30,
    notes: 'Strenuous 8mi RT — dramatic summit views of Cascade foothills and Snoqualmie Valley',
    image: WIKI('3/39/Mount_Si_from_the_south.jpg/800px-Mount_Si_from_the_south.jpg'),
  },
  {
    id: 'tiger-mountain',
    name: 'Tiger Mountain — West Tiger 3',
    category: 'nature', subcategory: 'Forests & Trails',
    lat: 47.5010, lng: -121.9805, distanceMiles: 25,
    notes: 'Dense Northwest forest opens to a bald summit with Lake Sammamish and Cascade views',
    image: UNS('1441974231531-c6227db76b6e'),
  },

  // ── NATURE: City Parks & Forests ─────────────────────────────────────────
  {
    id: 'seward-park',
    name: 'Seward Park',
    category: 'nature', subcategory: 'City Parks & Forests',
    lat: 47.5513, lng: -122.2530, distanceMiles: 7,
    notes: '300-acre old-growth forest peninsula — eagle nests + full downtown skyline across Lake Washington',
    image: UNS('1464822759023-fed622ff2c3b'),
  },
  {
    id: 'lincoln-park',
    name: 'Lincoln Park',
    category: 'nature', subcategory: 'City Parks & Forests',
    lat: 47.5289, lng: -122.3926, distanceMiles: 8,
    notes: 'Puget Sound beachfront + forested bluff — Olympic Mountains as your backdrop at sunset',
    image: UNS('1520038410233-7141be7e6f97'),
  },
  {
    id: 'carkeek-park',
    name: 'Carkeek Park',
    category: 'nature', subcategory: 'City Parks & Forests',
    lat: 47.7124, lng: -122.3763, distanceMiles: 8,
    notes: 'Driftwood beach + old-growth ravine — passing freight trains add drama, minimal crowds',
    image: UNS('1506905925346-21bda4d32df4'),
  },
  {
    id: 'bellevue-botanical',
    name: 'Bellevue Botanical Garden',
    category: 'nature', subcategory: 'City Parks & Forests',
    lat: 47.5935, lng: -122.1699, distanceMiles: 12,
    notes: 'Manicured paths, footbridges, and seasonal blooms — polished garden aesthetic year-round',
    image: UNS('1476067897447-90eb35ff6a70'),
  },

  // ── NATURE: Lakes & Rivers ────────────────────────────────────────────────
  {
    id: 'lake-serene',
    name: 'Lake Serene',
    category: 'nature', subcategory: 'Lakes & Rivers',
    lat: 47.8198, lng: -121.2668, distanceMiles: 55,
    notes: 'Pristine glacial lake below Index Town Wall — glass-still mirror reflections on calm mornings',
    image: UNS('1501854140801-50d01698950b'),
  },
  {
    id: 'green-lake',
    name: 'Green Lake Park',
    category: 'nature', subcategory: 'Lakes & Rivers',
    lat: 47.6781, lng: -122.3345, distanceMiles: 3,
    notes: 'Urban lake with sunrise reflections, herons, and swans — a perfect first-light shoot in the city',
    image: UNS('1476067897447-90eb35ff6a70'),
  },
  {
    id: 'magnuson-park',
    name: 'Magnuson Park',
    category: 'nature', subcategory: 'Lakes & Rivers',
    lat: 47.6847, lng: -122.2580, distanceMiles: 7,
    notes: 'Mile-long Lake Washington shoreline with open meadow — great first-light reflections and wide skies',
    image: UNS('1697729926633-1d9048a2d60a'),
  },
];

export const WEBCAMS = [
  {
    id: 'nps-paradise',
    label: 'Mt Rainier — Paradise',
    sublabel: 'National Park Service',
    type: 'img',
    url: 'https://www.nps.gov/webcams-mora/mountain.jpg',
    sourceUrl: 'https://www.nps.gov/mora/learn/photosmultimedia/webcams.htm',
  },
  {
    id: 'nps-east',
    label: 'Mt Rainier — East View',
    sublabel: 'National Park Service',
    type: 'img',
    url: 'https://www.nps.gov/webcams-mora/east.jpg',
    sourceUrl: 'https://www.nps.gov/mora/learn/photosmultimedia/webcams.htm',
  },
  {
    id: 'nps-tatoosh',
    label: 'Mt Rainier — Tatoosh Range',
    sublabel: 'National Park Service',
    type: 'img',
    url: 'https://www.nps.gov/webcams-mora/tatoosh.jpg',
    sourceUrl: 'https://www.nps.gov/mora/learn/photosmultimedia/webcams.htm',
  },
  {
    id: 'uw-rainier',
    label: 'UW Campus — Mt Rainier View',
    sublabel: 'UW Atmospheric Sciences',
    type: 'img',
    url: 'https://a.atmos.washington.edu/data/images/webcam2_latest.jpg',
    sourceUrl: 'https://a.atmos.washington.edu/data/webcams.html',
  },
  {
    id: 'wsdot-snq-east',
    label: 'Snoqualmie Pass — East',
    sublabel: 'Washington State DOT',
    type: 'img',
    url: 'https://images.wsdot.wa.gov/airports/hyakeast.jpg',
    sourceUrl: 'https://wsdot.wa.gov/travel/real-time/mountainpasses/Snoqualmie',
  },
  {
    id: 'wsdot-snq-west',
    label: 'Snoqualmie Pass — West',
    sublabel: 'Washington State DOT',
    type: 'img',
    url: 'https://images.wsdot.wa.gov/airports/hyakwest.jpg',
    sourceUrl: 'https://wsdot.wa.gov/travel/real-time/mountainpasses/Snoqualmie',
  },
];
